# Generated by Django 5.1.6 on 2025-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_times',
            field=models.TextField(),
        ),
    ]
