# Generated by Django 5.1.6 on 2025-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_doctor_available_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
