# Generated by Django 5.1.6 on 2025-03-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_duration',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
